sudo: required
services:
  - docker
before_install:
  - docker build -t dandakiran/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true dandakiran/docker-react npm run test -- --coverage

